# Generated by Django 5.1.2 on 2024-10-12 22:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='timestamp',
            new_name='create_date',
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='task',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='updated',
        ),
        migrations.AddField(
            model_name='todo',
            name='cancel_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='todo',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='todo',
            name='status',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='todo',
            name='tg_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=180),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='todo',
            name='tg_name',
            field=models.CharField(default=1, max_length=180),
            preserve_default=False,
        ),
    ]
