# Generated by Django 5.1.2 on 2024-10-12 23:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_api', '0003_alter_todo_status_alter_todo_tg_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Todo',
            new_name='Geek',
        ),
    ]
